-- Exercicios Realizados em Prova de Logica de Banco de Dados enviada em Agosto

--9)

SELECT CDCLICODIGO AS Codigo, CDCLINOME AS Nome, CDCLICIDADE AS Cidade
FROM CDCLIENTE
WHERE CDCLIATIVO = 1 AND UPPER(CDCLICIDADE) = 'GOIÁS';

-- 10) A) A é muitos para 1
-- 10) B) [X] Um cliente pode estar cadastrado e não ter nenhum atendimento;

 
-- 11)A)

SELECT CDFNOME AS NomeFuncionario
FROM CDFUNCIONARIO
WHERE CDFCODIGO NOT IN (
    SELECT LCAFUNCIONARIO
    FROM LCATENDIMENTO
);

--B)

SELECT 
  CD.CDCLINOME AS NomeCliente, 
  COALESCE((SELECT COUNT(*) FROM LCATENDIMENTO LA WHERE LA.LCACLIENTE = CD.CDCLICODIGO), 0) AS QuantidadeAtendimentos
FROM CDCLIENTE CD;

--C)

CREATE INDEX idx_datahora_atendimento ON LCATENDIMENTO (LCADATAHORA);

SELECT CD.CDCLINOME AS NomeCliente, LA.LCADATAHORA AS DataHoraAtendimento
FROM CDCLIENTE CD
INNER JOIN LCATENDIMENTO LA ON CD.CDCLICODIGO = LA.LCACLIENTE
WHERE LA.LCADATAHORA BETWEEN '2011-01-01 00:00:00' AND '2011-02-28 23:59:59'
   OR LA.LCADATAHORA BETWEEN '2011-07-01 00:00:00' AND '2011-12-31 23:59:59';
